name: "P6 GHA: Builds a CDKTF App"
description: "P6 GHA: Builds a CDKTF App"
author: "Philip M. Gollucci"
inputs:
  aws_region:
    description: "AWS region for deployment"
    required: false
    default: "us-east-1"
  aws_role:
    description: "AWS role to assume"
    required: true
  aws_session_name:
    description: "Session name for the AWS role"
    required: true
  cdk_deploy_account:
    description: "AWS CDK deploy account"
    required: true
  cdk_deploy_region:
    description: "AWS CDK deploy region"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2
    - name: Install Node.js
      shell: bash
      run: |
        set +e
        curl -fsSL https://nodejs.org/dist/v22.11.0/node-v22.11.0-linux-x64.tar.xz -o node-v22.11.0-linux-x64.tar.xz
        sudo tar -xJf node-v22.11.0-linux-x64.tar.xz -C /usr/local
        ls -alFh /usr/local
        sudo chmod -R 777 /usr/local/node-v22.11.0-linux-x64
        echo "/usr/local/node-v22.11.0-linux-x64/bin" >> $GITHUB_PATH
    - name: Corepack
      shell: bash
      run: |
        set +e
        echo $PATH
        which corepack
        sudo /usr/local/node-v22.11.0-linux-x64/bin/corepack enable
        sudo /usr/local/node-v22.11.0-linux-x64/bin/corepack prepare pnpm@latest --activate
    - name: Restore NPM node_modules
      uses: actions/cache/restore@v4.1.2
      with:
        path: node_modules
        key: ${{ runner.os }}-pnpm-node_modules-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-node_modules-
    - name: Check Node
      shell: bash
      run: |
        set +e
        which node
        which npm
        which pnpm
        which corepack
        node -v
        npm -v
        pnpm --version
        corepack --version
        echo $PATH
    - name: Install pnpm and dependencies
      shell: bash
      run: pnpm install
    - name: Cache NPM dependencies
      uses: actions/cache@v4.1.2
      with:
        path: node_modules
        key: ${{ runner.os }}-pnpm-node_modules-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-node_modules-
    - name: CDKTF bootstrap
      shell: bash
      run: |
        /usr/local/node-v22.11.0-linux-x64/bin/npm install --global cdktf-cli@latest
        which cdktf
        cdktf --version
    - name: Assume role using OIDC
      uses: aws-actions/configure-aws-credentials@v4.0.2
      with:
        aws-region: ${{ inputs.aws_region }}
        role-to-assume: ${{ inputs.aws_role }}
        role-session-name: ${{ inputs.aws_session_name }}
    - name: OpenTofu
      uses: opentofu/setup-opentofu@v1.0.4
      with:
        tofu_version: 1.8.6
    - name: Run build
      shell: bash
      env:
        CDKTF_LOG_LEVEL: debug
        CDK_DEPLOY_ACCOUNT: ${{ inputs.cdk_deploy_account }}
        CDK_DEPLOY_REGION: ${{ inputs.cdk_deploy_region }}
        AWS_REGION: ${{ inputs.aws_region }}
        TERRAFORM_BINARY_NAME: tofu
      run: pnpm run deploy
