name: "P6 GHA: Builds a CDKTF App"
description: "P6 GHA: Builds a CDKTF App"
author: "Philip M. Gollucci"
inputs:
  aws_region:
    description: "AWS region for deployment"
    required: false
    default: "us-east-1"
  aws_role:
    description: "AWS role to assume"
    required: true
  aws_session_name:
    description: "Session name for the AWS role"
    required: true
  cdk_deploy_account:
    description: "AWS CDK deploy account"
    required: true
  cdk_deploy_region:
    description: "AWS CDK deploy region"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2
    - name: Node
      uses: p6m7g8-actions/node-setup@main
    - name: CDKTF bootstrap
      shell: bash
      run: |
        /usr/local/node-v22.11.0-linux-x64/bin/npm install --global cdktf-cli@latest
        which cdktf
        cdktf --version
    - name: Assume role using OIDC
      uses: aws-actions/configure-aws-credentials@v4.0.2
      with:
        aws-region: ${{ inputs.aws_region }}
        role-to-assume: ${{ inputs.aws_role }}
        role-session-name: ${{ inputs.aws_session_name }}
    - name: OpenTofu
      uses: opentofu/setup-opentofu@v1.0.4
      with:
        tofu_version: 1.8.6
    - name: Run build
      shell: bash
      env:
        CDKTF_LOG_LEVEL: debug
        CDK_DEPLOY_ACCOUNT: ${{ inputs.cdk_deploy_account }}
        CDK_DEPLOY_REGION: ${{ inputs.cdk_deploy_region }}
        AWS_REGION: ${{ inputs.aws_region }}
        TERRAFORM_BINARY_NAME: tofu
      run: pnpm run deploy
